flowchart LR
    A[fa:fa-user Usuario]
    B((Executar isValid))
    C((Validar e-mail com ValidateEmail))
    D((Comparar senha com DEFAULT_PASSWORD))

    A -->|informar e-mail e senha| B
    B -.->|"<<include>>"| C
    B -.->|"<<include>>"| D
    B -->|retorno true ou false| A