flowchart TD
    A[fa:fa-user Usuário]
    B(fa:fa-box LeituraCSVEstados)
    C(fa:fa-box-open lerEApresentar)

    A -->| arquivo CSV | B
    B -->| código UF, sigla, nome | C
    C -->| exibe na tela | A
