classDiagram
    ClientRegistration : -SEPARATOR String
    ClientRegistration : -filePath String
    ClientRegistration : +setFilePath(path String) void
    ClientRegistration : +save(name String, cpf String, email String) void throws IOException